#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $prefix = "sys_";
    my $name = shift;
    if ($name eq "sbrk") {
	print ".global $prefix$name\n";
	print "$prefix$name:\n";
    } else {
	print ".global $name\n";
	print "$name:\n";
    }
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}

entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
# 注意：getpid 没有 entry - 它由 user/getpid.c 直接读 USYSCALL 页
entry("sbrk");
entry("pause");
entry("uptime");
entry("sync");
# Lab syscall additions
entry("trace");
entry("sysinfo");
# Lab traps additions
entry("sigalarm");
entry("sigreturn");
# Lab pgtbl additions
entry("pgaccess");
# Lab fs additions
entry("symlink");
# Lab mmap additions
entry("mmap");
entry("munmap");
# Lab util additions
entry("sleep");
